INSERT INTO public.bl_se_type (setype, semaster, mastersetypeid, defaultlabel, description, setypecategory, market, direction, metered, otherlabel, standardlabel) VALUES ('BILLABLE_CHARGE', false, 'CONSUMPTION', 'Element de service - Charges facturables', 'Charge facturable sous forme de montant fixe', 'BILLABLE_CHARGE', '*', 'RANCKING', false, NULL, NULL);
INSERT INTO public.bl_se_type (setype, semaster, mastersetypeid, defaultlabel, description, setypecategory, market, direction, metered, otherlabel, standardlabel) VALUES ('CONSUMPTION', true, NULL, 'Element de service - Part Proportionnelle', 'Quantité Proportionnel à la consommation', 'CONSUMPTION', '*', 'RANCKING', true, NULL, NULL);
INSERT INTO public.bl_se_type (setype, semaster, mastersetypeid, defaultlabel, description, setypecategory, market, direction, metered, otherlabel, standardlabel) VALUES ('SUBSCRIPTION', false, 'CONSUMPTION', 'Element de service - Part Fixe', 'Quantité Proportionnel au temps', 'SUBSCRIPTION', '*', 'RANCKING', false, NULL, NULL);
INSERT INTO public.bl_se_type (setype, semaster, mastersetypeid, defaultlabel, description, setypecategory, market, direction, metered, otherlabel, standardlabel) VALUES ('COST_ON_CONSUMPTION', false, 'CONSUMPTION', 'Element de service - Coût sur par proportionelle', NULL, 'CONSUMPTION', '*', 'RANCKING', true, NULL, NULL);
INSERT INTO public.bl_se_type (setype, semaster, mastersetypeid, defaultlabel, description, setypecategory, market, direction, metered, otherlabel, standardlabel) VALUES ('DISCOUNT_ON_CONSUMPTION', false, 'CONSUMPTION', 'Element de service - Remise sur la consommation', 'Remise sur la consommation', 'CONSUMPTION', '*', 'RANCKING', true, NULL, 'Element de service - Remise sur la consommation');
INSERT INTO public.bl_se_type (setype, semaster, mastersetypeid, defaultlabel, description, setypecategory, market, direction, metered, otherlabel, standardlabel) VALUES ('PAYMENT_PLAN', false, 'CONSUMPTION', 'Element de service - Plan de paiement', 'Echéancier de paiement/Echelonnement de dette', 'PAYMENT_PLAN', '*', 'RANCKING', false, NULL, 'Element de service - Plan de paiement');
INSERT INTO public.bl_se_type (setype, semaster, mastersetypeid, defaultlabel, description, setypecategory, market, direction, metered, otherlabel, standardlabel) VALUES ('FEE_ON_CONSUMPTION', false, 'CONSUMPTION', 'Element de service - Frais sur part proportionnelle', 'Frais additionnels sur la consommation', 'CONSUMPTION', '*', 'RANCKING', true, NULL, 'Element de service - Frais sur part proportionnelle');
INSERT INTO public.bl_se_type (setype, semaster, mastersetypeid, defaultlabel, description, setypecategory, market, direction, metered, otherlabel, standardlabel) VALUES ('TAX_ON_CONSUMPTION', false, 'CONSUMPTION', 'Element de service - Taxe sur part fixe', 'Taxe sur part fixe', 'SUBSCRIPTION', '*', 'RANCKING', true, NULL, 'Element de service - Taxe sur part fixe');
INSERT INTO public.bl_se_type (setype, semaster, mastersetypeid, defaultlabel, description, setypecategory, market, direction, metered, otherlabel, standardlabel) VALUES ('TAX_ON_SUBSCRIPTION', false, 'CONSUMPTION', 'Element de service - Taxe sur part proportionnelle', 'Taxe sur part proportionnelle', 'CONSUMPTION', '*', 'RANCKING', false, NULL, 'Element de service - Taxe sur part proportionnelle');
